apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spre-gosys
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 20
  readiness:
    path: /isready
    initialDelay: 20
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/spre-gosys/tbd
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvspregosys
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_RAPID_TOPIC
      value: helse-rapid-v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: spre-gosys-v1
    - name: STS_URL
      value: http://security-token-service.default.svc.nais.local
    - name: JOARK_BASE_URL
      value: https://dokarkiv-q1.nais.preprod.local
